logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: 192.168.5.67 # 你的虚拟机IP
    port: 5673 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    listener:
      simple:
        prefetch: 1
        enabled: true # 开启消费者失败重试
        initial-interval: 1000ms # 初识的失败等待时长为1秒
        multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
        max-attempts: 3 # 最大重试次数
        stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false